"""Ports for the commercial hierarchy: partners, tenants, and how each was provisioned."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from ivaas.domain.tenancy import Partner, ProvisioningRecord, Tenant


class TenantStore(Protocol):
    async def get(self, tenant_id: UUID) -> Tenant | None: ...

    async def get_by_slug(self, slug: str) -> Tenant | None: ...

    async def list_all(self, *, partner_id: UUID | None = None) -> list[Tenant]: ...

    async def save(self, tenant: Tenant) -> None: ...

    async def get_partner(self, partner_id: UUID) -> Partner | None: ...

    async def list_partners(self) -> list[Partner]: ...

    async def save_partner(self, partner: Partner) -> None: ...

    async def get_provisioning(self, idempotency_key: str) -> ProvisioningRecord | None: ...

    async def save_provisioning(self, record: ProvisioningRecord) -> None: ...
